### ISSUE TITLE
Missing Parentheses in print statement

### ISSUE THREAD

**Issue by rkalamdani** [vishnubob/python-midi#116]
The line in setup.py:

print "No sequencer available for '%s' platform." % platform

should be updated to

print ("No sequencer available for '%s' platform." % platform)
 
to avoid this error when using pip install python-midi:

pip install python-midi
Collecting python-midi
  Downloading python-midi-v0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\owner-pc\AppData\Local\Temp\pip-build-wvrojn4c\python-midi\setup.py", line 42
        print "No sequencer available for '%s' platform." % platform
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\owner-pc\AppData\Local\Temp\pip-build-wvrojn4c\python-midi\

**Comment by yourGrigor** [comment]
Didn't saw there is already a fix.
Look at the feature/python3 branch.

**Comment by DannyDannyDanny** [comment]
`pip install git+https://github.com/vishnubob/python-midi@feature/python3`
