### ISSUE TITLE
I get AttributeError: module 'midi' has no attribute 'read_midifile'

### ISSUE THREAD

**Issue by shirishr** [vishnubob/python-midi#124]
Here is a traceback:

(py35) C:\Users\shiri\Documents\AI_Composer-master>python main.py
Parsing train...
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    nottingham_util.create_model()
  File "C:\Users\shiri\Documents\AI_Composer-master\nottingham_util.py", line 512, in create_model
    prepare_nottingham_pickle(time_step, verbose=True)
  File "C:\Users\shiri\Documents\AI_Composer-master\nottingham_util.py", line 69, in prepare_nottingham_pickle
    parsed = parse_nottingham_directory("data/Nottingham/{}".format(d), time_step, verbose=False)
  File "C:\Users\shiri\Documents\AI_Composer-master\nottingham_util.py", line 148, in parse_nottingham_directory
    for f in files ]
  File "C:\Users\shiri\Documents\AI_Composer-master\nottingham_util.py", line 148, in <listcomp>
    for f in files ]
  File "C:\Users\shiri\Documents\AI_Composer-master\nottingham_util.py", line 169, in parse_nottingham_to_sequence
    pattern = midi.read_midifile(input_filename)
AttributeError: module 'midi' has no attribute 'read_midifile'

**Comment by shirishr** [comment]
Issue resolved by using:
 install git+https://github.com/vishnubob/python-midi@feature/python3
