### ISSUE TITLE
Could not import midi

### ISSUE THREAD

**Issue by aljohani003** [vishnubob/python-midi#139]
Hi. 
I am new to python
when I tried to import midi this message shown
 $ pip install midi
Collecting midi
  Could not find a version that satisfies the requirement midi (from versions: )
No matching distribution found for midi

I tried also this
$ pip install python-midi
Collecting python-midi
  Using cached python-midi-v0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ikrcdmie/python-midi/setup.py", line 42
        print "No sequencer available for '%s' platform." % platform
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "No sequencer available for '%s' platform." % platform)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ikrcdmie/python-midi/

I am using python 2.7

**Comment by owennewo** [comment]
I saw the same issue, except I was using python 3.  The print statement above is not valid in Python 3 it needs parenthesis i.e.
`print ("No sequencer available for '%s' platform." % platform)`

**Comment by fengzean** [comment]
pip install git+https://github.com/vishnubob/python-midi@feature/python3
should solve this problem

**Comment by trthhrtz** [comment]
If you have problems with install @fengzean way, check that `sudo apt-get install  libasound2-dev swig` are installed

**Comment by Andyz239** [comment]
try：( for python3+ )
pip3 install git+https://github.com/vishnubob/python-midi@feature/python3

**Comment by Omar-Dasser** [comment]
try this instead : 
pip install py-midi

**Comment by manhongxiang** [comment]
> try this instead :
> pip install py-midi

It works. Thank you!
