### ISSUE TITLE
ModuleNotFoundError: No module named 'containers' in Ubuntu 18.04

### ISSUE THREAD

**Issue by varshneydevansh** [vishnubob/python-midi#151]
```
devansh@varshney:~$ mididump.py mary.mid
Traceback (most recent call last):
  File "/home/devansh/anaconda3/bin/mididump.py", line 5, in <module>
    import midi
  File "/home/devansh/anaconda3/lib/python3.6/site-packages/midi/__init__.py", line 1, in <module>
    from containers import *
ModuleNotFoundError: No module named 'containers'
```

**Comment by MorganCZY** [comment]
how did you solve this error?

**Comment by Rin18** [comment]
Did anyone manage to solve this?
