### ISSUE TITLE
upgrade the setup.py to suit python 3

### ISSUE THREAD

**Issue by ucasiggcas** [vishnubob/python-midi#157]
hello 
In the setup.py file,  after print should be () ,
Please upgrade it 
If not ,the error is below
Processing d:\python\scripts\python-midi-v0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ENJOYT~1\AppData\Local\Temp\pip-req-build-107jasg5\setup.py", line 42
        print "No sequencer available for '%s' platform." % platform
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No sequencer available for '%s' platform." % platform)?

**Comment by mgbvox** [comment]
Hey - python 2 is now officially dead, any chance this is going to be updated?
