### ISSUE TITLE
import midi.sequencer as sequencer ImportError: No module named sequencer

### ISSUE THREAD

**Issue by avaziyi** [vishnubob/python-midi#16]
how to solve the problem when i tried the “scripts/”~
thanks

**Comment by ShupingRuan** [comment]
Has this problem been solved? I tried  "midiplay.py 128 0 mary.mid" and got this error "ImportError: No module named sequencer".

**Comment by vishnubob** [comment]
The only platform that supports the sequencer is on Linux.  If you using python-midi on windows or OSX, there is no sequencer support.

**Comment by L4in** [comment]
I am using a Linux distribution and I also have the sequencer problem.

````
  File "/usr/local/bin/mididump.py", line 5, in <module>
    import midi
  File "build/bdist.linux-x86_64/egg/midi/__init__.py", line 6, in <module>
ImportError: No module named sequencer
````

The repo is freshly cloned and the sequencer is mentioned multiple times as a console of `python setup.py install`.

I took a look at the [Travis tests](https://travis-ci.org/vishnubob/python-midi/jobs/74638509) and the sequencer is also a problem on this Linux machine.

**Comment by vishnubob** [comment]
Are you sure you have a clean repository?  Perhaps you have installed an older version of the library, and you need to clean it out first?  If you look at the current version of [__init__.py](https://github.com/vishnubob/python-midi/blob/master/src/__init__.py), there is no "line 6" as reported by your traceback, so it doesn't look like you are executing the most recent code base.  You might try installing under a virtualenv, and seeing if that clears up the problem.  If it does, you will probably need to hunt through your python path, removing older versions of the midi package.

**Comment by L4in** [comment]
I had no memory of installing a midi egg, however `pip uninstall midi` did remove something I don't think I ever installed willingly. Perhaps some other project I installed did it on its own.
Anyway, my problem is solved. Thanks a lot.

**Comment by fornof** [comment]
just did a git  clone and then python setup.py , 2 errors, first was an error saying the version should be 2.3 ... instead of v2.3 , when I removed that I got a sequencer error stated above (I am on a mac) 

can you hook up a sequencer used in this project? http://pedrokroger.net/converting-midi-files-mp3-mac-os/

**Comment by Irides-Chromium** [comment]
Experiencing the same problem. Not in the `__init__.py`, but rather in the `mididumphw.py`.
I tried to `dir(midi)` after importing, but no `sequencer`. Maybe there is an error in the code.
    Traceback (most recent call last):
      File "./mididumphw.py", line 5, in <module>
        import midi.sequencer as sequencer
    ImportError: No module named midi.sequencer

**Comment by Mr-Kickass** [comment]
Trying to install midi, using python version 3.5.2 but Im getting an error when I use 'import midi'  <pre> File "C:\Users\vashwin\AppData\Local\Continuum\Anaconda3\lib\site-packages\mid
i-0.2.3-py3.5.egg\midi\__init__.py", line 1, in <module>
ImportError: No module named 'containers'</pre>

**Comment by TheRealPhoneCall** [comment]
Same problem for me. I ran midiplay, midilisten, And I had a clean and recent clone too.

**Comment by bootsch** [comment]
Hi There,
I understand there's no sequencer for OSX but I would still like to use the module.
To explain, I'm using the midi stream to create 3D animation in Maya. I have been using a nice module called 'midiparser.py' by  Sean D. Spencer but it does not handle all the files I have.

So far python-midi does and I'm happy to have found it. Thanks. But instead of writting my own handling of the package/track lists I'm looking to use the sequencer.py.

I can install it myself but it would be nice to include it on install after all maybe (?)

**Comment by widestreid00** [comment]
Getting this error running on unix 

```
brian@brian-VirtualBox:~/Downloads$ mididumphw.py
Traceback (most recent call last):
  File "/usr/local/bin/mididumphw.py", line 4, in <module>
    __import__('pkg_resources').run_script('midi==0.2.3', 'mididumphw.py')
  File "/home/brian/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/brian/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/midi-0.2.3-py3.8.egg/EGG-INFO/scripts/mididumphw.py", line 5, in <module>
ModuleNotFoundError: No module named 'midi.sequencer'
```


although I don't know why because I was able to run 
`pip install pymidi `

I was also able to also run
`mididump.py `

**Comment by nsputnik** [comment]
`No sequencer available for 'darwin' platform.`
Has one been written yet?
