### ISSUE TITLE
pip3 package doesn't work

### ISSUE THREAD

**Issue by RogerLevy** [vishnubob/python-midi#186]
Here is what I'm getting.  I've tried it with and without sudo.

```pi@raspberrypi:~/.local/lib/python3.7/site-packages $ sudo pip3 install python3-midi==0.2.5
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting python3-midi==0.2.5
  Using cached https://files.pythonhosted.org/packages/44/97/52e7742febb4a3b66d66160bfbf88dd80657fa1866d7aedaaa80e0cef547/python3_midi-0.2.5-py3-none-any.whl
Installing collected packages: python3-midi
Successfully installed python3-midi-0.2.5
pi@raspberrypi:~/.local/lib/python3.7/site-packages $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import midi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'midi'
>>> import python3_midi
>>> python3_midi.sequencer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'python3_midi' has no attribute 'sequencer'
```

**Comment by souris-dev** [comment]
The package you installed is an entirely different package it seems.

**Comment by lifeModder19135** [comment]
There were like 5-10 different 'python-midi' packages on Pypi last time I checked.
