### ISSUE TITLE
python-midi crashes when encountering an unknown header

### ISSUE THREAD

**Issue by SamusAranX** [vishnubob/python-midi#88]
I'm currently working on a project that involves MIDI files made by Sony Ericsson phones' MusicDJ application. These files contain a non-standard SEM1 header that causes python-midi to drop dead:

    Traceback (most recent call last):
      File "/Users/peterwunder/Desktop/musicdj.py", line 6, in <module>
        pattern = midi.read_midifile("MIDITest_SEM1.mid")
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/midi/fileio.py", line 176, in read_midifile
        return read_midifile(inp)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/midi/fileio.py", line 178, in read_midifile
        return reader.read(midifile)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/midi/fileio.py", line 11, in read
        self.parse_track(midifile, track)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/midi/fileio.py", line 46, in parse_track
        trksz = self.parse_track_header(midifile)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/midi/fileio.py", line 39, in parse_track_header
        raise TypeError("Bad track header in MIDI file: ",magic)
    TypeError: ('Bad track header in MIDI file: ', b'SEM1')

It'd be great if there was a way to tell python-midi to just ignore bad or unknown headers.

I've attached the file in question. It should be playable by most players. The SEM1 header is at position 0xE and is 270 bytes long. The header structure is 
("SEM1", 4 bytes) (length, 4 bytes) (bunch of as of yet unknown data).
[MIDITest_SEM1.zip](https://github.com/vishnubob/python-midi/files/247511/MIDITest_SEM1.zip)

**Comment by vishnubob** [comment]
Can you point to any other application that can load the file as a MIDI file?

**Comment by SamusAranX** [comment]
I'm not sure I understand what you mean. Logic Pro X can't load the file, but QuickTime Player 7 and [my own app](https://github.com/SamusAranX/MinimalMIDIPlayer) can.
